# Generated by Django 5.1.3 on 2025-04-18 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_address_phone_cartitem_updated_at_alter_order_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='phone',
            new_name='mobile',
        ),
    ]
