databases:
- name: chopchop-db
  databaseName: chopchop_db_osmo
  user: chopchop_db_osmo_user
  plan: free
  region: virginia
  ipAllowList:
  - source: 0.0.0.0/0
    description: everywhere
  postgresMajorVersion: "16"
version: "1"
